### ISSUE TITLE
Update this quarter? thanks

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/sqliteport#3]
SQLite
Date	Version 
2023-05-16	3.42.0
2023-03-22	3.41.2
2023-03-10	3.41.1
2023-02-21	3.41.0
2022-12-28	3.40.1
2022-11-16	3.40.0

SQLite version 3.40.0 2022-11-16 12:10:08
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .exit

**Comment by IgorTodorovskiIBM** [comment]
Updated to 3.42: https://github.com/ZOSOpenTools/sqliteport/releases/tag/Releaseline_sqliteport_1068

**Comment by gngrossi** [comment]
-- Loading resources from /u/@02858/.sqliterc
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .exit
